apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: clickhouse
resources:
  - 00-namespace.yaml
  - clickhouse.yaml
  - seaweedfs.yaml
  - ingester.yaml
  - recorder-binance.yaml
  - recorder-bybit.yaml
  - observability.yaml
