//! Pinned sbe-tool is the independent oracle for the versioned nested L3 book
//! that the memoized random-access decoder is evaluated against.
//!
//! Two halves, matching the two ways the oracle can be wrong:
//!
//! * **Exact encode** — ergo-sbe and sbe-tool encode the identical dense,
//!   four-level-deep book and must produce byte-identical frames. This pins the
//!   wire layout of a schema with `sinceVersion` groups and var-data at every
//!   depth. **At v3 only**: sbe-tool's generated Rust encoder writes the
//!   codec's compiled `blockLength` and schema version, so it cannot emit a
//!   v0-v2 frame from the v3 schema. Older acting versions are covered by the
//!   cross-decode half below, and ergo-sbe's own version projection is proven
//!   byte-identical against per-version schemas in
//!   `sbe/tests/versioned_l3_cache_test.rs`
//!   (`snapshot_encoder_matches_encode_version_filter`).
//! * **Ordered cross-decode** — sbe-tool decodes ergo-sbe's bytes strictly in
//!   canonical wire order, at every acting version 0–3, and must see every
//!   value. This is the ordered reference that ergo-sbe's schema-order decode
//!   is checked against.
//!
//! Arbitrary field-order decoding is then differentiated against ergo-sbe's own
//! schema-order decode in `sbe/benchmarks/tests/versioned_l3_differential_test.rs`,
//! which is what closes the loop: schema order equals sbe-tool here, and every
//! other order equals schema order there.
//!
//! Reference crate: `sbe/tests/sbe_tool_reference/versioned_l3` (package
//! `parity_versioned_l3`), regenerated by
//! `scripts/regenerate-sbe-tool-reference.sh` from the pinned submodule.

mod common;
use common::{Paths, dual_encode_run_modules, generate, generate_domain_with};

/// ergo-sbe modules: the full v3 codec plus encoders filtered to versions 0–2.
fn modules() -> Vec<(String, String)> {
    let mut out = vec![(
        "ergo".to_owned(),
        generate(&Paths::versioned_l3_schema(3), "ergo").1,
    )];
    for version in 0u16..=2 {
        let name = format!("enc{version}");
        let (_schema, src) = generate_domain_with(&Paths::versioned_l3_schema(3), &name, |c| {
            c.with_encode_version(version)
        });
        out.push((name, src));
    }
    out
}

fn run(test_name: &str, body: &str) {
    let mods = modules();
    let pairs: Vec<(&str, &str)> = mods.iter().map(|(n, s)| (n.as_str(), s.as_str())).collect();
    dual_encode_run_modules(
        test_name,
        &pairs,
        "versioned_l3",
        &format!("{BOOK}\n{ENCODERS}\n{body}"),
    );
}

/// The dense book both generators encode: every group populated somewhere and
/// empty somewhere, var-data empty and non-empty at every depth.
const BOOK: &str = r#"
struct Leg { qty: i64, reference: &'static [u8] }
struct Alloc { qty: i64, legs: &'static [Leg] }
struct Ord { qty: i64, allocations: &'static [Alloc], id: &'static [u8], trader: &'static [u8] }
struct Stat { fills: u64, qty: i64 }
struct Lvl {
    price: i64,
    qty: i64,
    participant: u64,
    orders: &'static [Ord],
    stats: &'static [Stat],
    venue: &'static [u8],
}
struct Row { ts: u64, code: u16 }

static BIDS: &[Lvl] = &[
    Lvl {
        price: 100,
        qty: 10,
        participant: 1,
        orders: &[
            Ord {
                qty: 5,
                allocations: &[
                    Alloc {
                        qty: 9,
                        legs: &[
                            Leg { qty: 3, reference: b"leg-alpha" },
                            Leg { qty: 4, reference: b"" },
                        ],
                    },
                    Alloc { qty: 7, legs: &[] },
                ],
                id: b"ord-0",
                trader: b"t0",
            },
            Ord { qty: 6, allocations: &[], id: b"", trader: b"trader-one" },
        ],
        stats: &[Stat { fills: 1, qty: 2 }, Stat { fills: 3, qty: 4 }],
        venue: b"XNAS",
    },
    Lvl { price: 101, qty: 0, participant: 2, orders: &[], stats: &[], venue: b"" },
    Lvl {
        price: 102,
        qty: 20,
        participant: 3,
        orders: &[Ord {
            qty: 7,
            allocations: &[Alloc { qty: 1, legs: &[Leg { qty: 2, reference: b"z" }] }],
            id: b"ord-2",
            trader: b"",
        }],
        stats: &[Stat { fills: 5, qty: 6 }],
        venue: b"XLON",
    },
];

static ASKS: &[Lvl] = &[
    Lvl {
        price: 200,
        qty: 30,
        participant: 4,
        orders: &[Ord {
            qty: 8,
            allocations: &[Alloc { qty: 4, legs: &[Leg { qty: 4, reference: b"ask-leg" }] }],
            id: b"ask-0",
            trader: b"ta",
        }],
        stats: &[],
        venue: b"BATS",
    },
    Lvl {
        price: 201,
        qty: 31,
        participant: 5,
        orders: &[],
        stats: &[Stat { fills: 7, qty: 8 }],
        venue: b"",
    },
];

static AUDIT: &[Row] = &[Row { ts: 11, code: 2 }, Row { ts: 13, code: 4 }];

const TIMESTAMP: u64 = 0x0102_0304_0506_0708;
const SEQUENCE: u64 = 42;
const EPOCH: u32 = 7;
const FLAGS: u32 = 0xDEAD_BEEF;
const SYMBOL: &[u8] = b"IBM";
const SOURCE: &[u8] = b"feed-a";
const CHECKSUM: &[u8] = b"";
const NOTE: &[u8] = b"note-text";

fn utf8(bytes: &[u8]) -> &str {
    core::str::from_utf8(bytes).expect("fixture text is UTF-8")
}
"#;

/// ergo-sbe encoders, one per acting version. Buffers are sized by the
/// generated `EncodedLength` builder and the result is cross-checked against
/// the encoder's own reported length.
const ENCODERS: &str = r#"
fn encode_v3() -> Result<Vec<u8>, Box<dyn std::error::Error>> {
    let len = ergo::L3BookEncodedLength::new()
        .bids_ragged(BIDS.len() as u16, |b| {
            for lvl in BIDS {
                b.add()?
                    .orders(|o| {
                        for ord in lvl.orders {
                            o.add()?
                                .allocations(|a| {
                                    for al in ord.allocations {
                                        a.add()?.legs(|l| {
                                            for leg in al.legs {
                                                l.add()?.leg_ref(leg.reference.len())?;
                                            }
                                            Ok(())
                                        })?;
                                    }
                                    Ok(())
                                })?
                                .order_id(ord.id.len())?
                                .trader_id(ord.trader.len())?;
                        }
                        Ok(())
                    })?
                    .stats(|s| { s.uniform(lvl.stats.len())?; Ok(()) })?
                    .venue(lvl.venue.len())?;
            }
            Ok(())
        })?
        .asks_ragged(ASKS.len() as u16, |b| {
            for lvl in ASKS {
                b.add()?
                    .ask_orders(|o| {
                        for ord in lvl.orders {
                            o.add()?
                                .ask_allocations(|a| {
                                    for al in ord.allocations {
                                        a.add()?.ask_legs(|l| {
                                            for leg in al.legs {
                                                l.add()?.leg_ref(leg.reference.len())?;
                                            }
                                            Ok(())
                                        })?;
                                    }
                                    Ok(())
                                })?
                                .order_id(ord.id.len())?
                                .trader_id(ord.trader.len())?;
                        }
                        Ok(())
                    })?
                    .ask_stats(|s| { s.uniform(lvl.stats.len())?; Ok(()) })?
                    .venue(lvl.venue.len())?;
            }
            Ok(())
        })?
        .audit(AUDIT.len() as u16)?
        .symbol(SYMBOL.len())?
        .source(SOURCE.len())?
        .checksum(CHECKSUM.len())?
        .note(NOTE.len())?
        .encoded_length_with_header();
    let mut buf = vec![0u8; len];
    let written = ergo::L3BookEncoder::try_wrap_and_apply_header(&mut buf, 0)?
        .fixed(&ergo::L3BookFixedFields {
            timestamp: TIMESTAMP,
            sequence: SEQUENCE,
            epoch: EPOCH,
            flags: FLAGS,
        })
        .bids(BIDS.len() as u16, |g| {
            for lvl in BIDS {
                g.add(|mut entry| {
                    entry.price(lvl.price).qty(lvl.qty).participant(lvl.participant);
                    entry
                        .orders(lvl.orders.len() as u16, |o| {
                            for ord in lvl.orders {
                                o.add(|mut e| {
                                    e.order_qty(ord.qty);
                                    e.allocations(ord.allocations.len() as u16, |a| {
                                        for al in ord.allocations {
                                            a.add(|mut ae| {
                                                ae.alloc_qty(al.qty);
                                                ae.legs(al.legs.len() as u16, |l| {
                                                    for leg in al.legs {
                                                        l.add(|mut le| {
                                                            le.leg_qty(leg.qty);
                                                            le.leg_ref(leg.reference)
                                                        })?;
                                                    }
                                                    Ok(())
                                                })
                                            })?;
                                        }
                                        Ok(())
                                    })?
                                    .order_id(ord.id)?
                                    .trader_id(ord.trader)
                                })?;
                            }
                            Ok(())
                        })?
                        .stats(lvl.stats.len() as u16, |s| {
                            for st in lvl.stats {
                                s.add(|mut e| {
                                    e.fill_count(st.fills).fill_qty(st.qty);
                                    Ok(())
                                })?;
                            }
                            Ok(())
                        })?
                        .venue(lvl.venue)
                })?;
            }
            Ok(())
        })?
        .asks(ASKS.len() as u16, |g| {
            for lvl in ASKS {
                g.add(|mut entry| {
                    entry.price(lvl.price).qty(lvl.qty).participant(lvl.participant);
                    entry
                        .ask_orders(lvl.orders.len() as u16, |o| {
                            for ord in lvl.orders {
                                o.add(|mut e| {
                                    e.order_qty(ord.qty);
                                    e.ask_allocations(ord.allocations.len() as u16, |a| {
                                        for al in ord.allocations {
                                            a.add(|mut ae| {
                                                ae.alloc_qty(al.qty);
                                                ae.ask_legs(al.legs.len() as u16, |l| {
                                                    for leg in al.legs {
                                                        l.add(|mut le| {
                                                            le.leg_qty(leg.qty);
                                                            le.leg_ref(leg.reference)
                                                        })?;
                                                    }
                                                    Ok(())
                                                })
                                            })?;
                                        }
                                        Ok(())
                                    })?
                                    .order_id(ord.id)?
                                    .trader_id(ord.trader)
                                })?;
                            }
                            Ok(())
                        })?
                        .ask_stats(lvl.stats.len() as u16, |s| {
                            for st in lvl.stats {
                                s.add(|mut e| {
                                    e.fill_count(st.fills).fill_qty(st.qty);
                                    Ok(())
                                })?;
                            }
                            Ok(())
                        })?
                        .venue(lvl.venue)
                })?;
            }
            Ok(())
        })?
        .audit(AUDIT.len() as u16, |g| {
            for row in AUDIT {
                g.add(|mut e| { e.ts(row.ts).code(row.code); Ok(()) })?;
            }
            Ok(())
        })?
        .symbol(SYMBOL)?
        .source(SOURCE)?
        .checksum(CHECKSUM)?
        .note(NOTE)?
        .encoded_length_with_header();
    assert_eq!(len, written, "v3 EncodedLength disagreed with the encoder");
    Ok(buf)
}

fn encode_v2() -> Result<Vec<u8>, Box<dyn std::error::Error>> {
    let len = enc2::L3BookEncodedLength::new()
        .bids_ragged(BIDS.len() as u16, |b| {
            for lvl in BIDS {
                b.add()?
                    .orders(|o| {
                        for ord in lvl.orders {
                            o.add()?
                                .allocations(|a| { a.uniform(ord.allocations.len())?; Ok(()) })?
                                .order_id(ord.id.len())?
                                .trader_id(ord.trader.len())?;
                        }
                        Ok(())
                    })?
                    .stats(|s| { s.uniform(lvl.stats.len())?; Ok(()) })?
                    .venue(lvl.venue.len())?;
            }
            Ok(())
        })?
        .asks_ragged(ASKS.len() as u16, |b| {
            for lvl in ASKS {
                b.add()?
                    .ask_orders(|o| {
                        for ord in lvl.orders {
                            o.add()?
                                .ask_allocations(|a| { a.uniform(ord.allocations.len())?; Ok(()) })?
                                .order_id(ord.id.len())?
                                .trader_id(ord.trader.len())?;
                        }
                        Ok(())
                    })?
                    .ask_stats(|s| { s.uniform(lvl.stats.len())?; Ok(()) })?
                    .venue(lvl.venue.len())?;
            }
            Ok(())
        })?
        .audit(AUDIT.len() as u16)?
        .symbol(SYMBOL.len())?
        .source(SOURCE.len())?
        .checksum(CHECKSUM.len())?
        .encoded_length_with_header();
    let mut buf = vec![0u8; len];
    let written = enc2::L3BookEncoder::try_wrap_and_apply_header(&mut buf, 0)?
        .fixed(&enc2::L3BookFixedFields {
            timestamp: TIMESTAMP,
            sequence: SEQUENCE,
            epoch: EPOCH,
        })
        .bids(BIDS.len() as u16, |g| {
            for lvl in BIDS {
                g.add(|mut entry| {
                    entry.price(lvl.price).qty(lvl.qty).participant(lvl.participant);
                    entry
                        .orders(lvl.orders.len() as u16, |o| {
                            for ord in lvl.orders {
                                o.add(|mut e| {
                                    e.order_qty(ord.qty);
                                    e.allocations(ord.allocations.len() as u16, |a| {
                                        for al in ord.allocations {
                                            a.add(|mut ae| { ae.alloc_qty(al.qty); Ok(()) })?;
                                        }
                                        Ok(())
                                    })?
                                    .order_id(ord.id)?
                                    .trader_id(ord.trader)
                                })?;
                            }
                            Ok(())
                        })?
                        .stats(lvl.stats.len() as u16, |s| {
                            for st in lvl.stats {
                                s.add(|mut e| {
                                    e.fill_count(st.fills).fill_qty(st.qty);
                                    Ok(())
                                })?;
                            }
                            Ok(())
                        })?
                        .venue(lvl.venue)
                })?;
            }
            Ok(())
        })?
        .asks(ASKS.len() as u16, |g| {
            for lvl in ASKS {
                g.add(|mut entry| {
                    entry.price(lvl.price).qty(lvl.qty).participant(lvl.participant);
                    entry
                        .ask_orders(lvl.orders.len() as u16, |o| {
                            for ord in lvl.orders {
                                o.add(|mut e| {
                                    e.order_qty(ord.qty);
                                    e.ask_allocations(ord.allocations.len() as u16, |a| {
                                        for al in ord.allocations {
                                            a.add(|mut ae| { ae.alloc_qty(al.qty); Ok(()) })?;
                                        }
                                        Ok(())
                                    })?
                                    .order_id(ord.id)?
                                    .trader_id(ord.trader)
                                })?;
                            }
                            Ok(())
                        })?
                        .ask_stats(lvl.stats.len() as u16, |s| {
                            for st in lvl.stats {
                                s.add(|mut e| {
                                    e.fill_count(st.fills).fill_qty(st.qty);
                                    Ok(())
                                })?;
                            }
                            Ok(())
                        })?
                        .venue(lvl.venue)
                })?;
            }
            Ok(())
        })?
        .audit(AUDIT.len() as u16, |g| {
            for row in AUDIT {
                g.add(|mut e| { e.ts(row.ts).code(row.code); Ok(()) })?;
            }
            Ok(())
        })?
        .symbol(SYMBOL)?
        .source(SOURCE)?
        .checksum(CHECKSUM)?
        .encoded_length_with_header();
    assert_eq!(len, written, "v2 EncodedLength disagreed with the encoder");
    Ok(buf)
}

fn encode_v1() -> Result<Vec<u8>, Box<dyn std::error::Error>> {
    let len = enc1::L3BookEncodedLength::new()
        .bids_ragged(BIDS.len() as u16, |b| {
            for lvl in BIDS {
                b.add()?
                    .orders(|o| {
                        for ord in lvl.orders {
                            o.add()?.order_id(ord.id.len())?.trader_id(ord.trader.len())?;
                        }
                        Ok(())
                    })?
                    .venue(lvl.venue.len())?;
            }
            Ok(())
        })?
        .asks_ragged(ASKS.len() as u16, |b| {
            for lvl in ASKS {
                b.add()?
                    .ask_orders(|o| {
                        for ord in lvl.orders {
                            o.add()?.order_id(ord.id.len())?.trader_id(ord.trader.len())?;
                        }
                        Ok(())
                    })?
                    .venue(lvl.venue.len())?;
            }
            Ok(())
        })?
        .symbol(SYMBOL.len())?
        .source(SOURCE.len())?
        .encoded_length_with_header();
    let mut buf = vec![0u8; len];
    let written = enc1::L3BookEncoder::try_wrap_and_apply_header(&mut buf, 0)?
        .fixed(&enc1::L3BookFixedFields {
            timestamp: TIMESTAMP,
            sequence: SEQUENCE,
            epoch: EPOCH,
        })
        .bids(BIDS.len() as u16, |g| {
            for lvl in BIDS {
                g.add(|mut entry| {
                    entry.price(lvl.price).qty(lvl.qty).participant(lvl.participant);
                    entry
                        .orders(lvl.orders.len() as u16, |o| {
                            for ord in lvl.orders {
                                o.add(|mut e| {
                                    e.order_qty(ord.qty);
                                    e.order_id(ord.id)?.trader_id(ord.trader)
                                })?;
                            }
                            Ok(())
                        })?
                        .venue(lvl.venue)
                })?;
            }
            Ok(())
        })?
        .asks(ASKS.len() as u16, |g| {
            for lvl in ASKS {
                g.add(|mut entry| {
                    entry.price(lvl.price).qty(lvl.qty).participant(lvl.participant);
                    entry
                        .ask_orders(lvl.orders.len() as u16, |o| {
                            for ord in lvl.orders {
                                o.add(|mut e| {
                                    e.order_qty(ord.qty);
                                    e.order_id(ord.id)?.trader_id(ord.trader)
                                })?;
                            }
                            Ok(())
                        })?
                        .venue(lvl.venue)
                })?;
            }
            Ok(())
        })?
        .symbol(SYMBOL)?
        .source(SOURCE)?
        .encoded_length_with_header();
    assert_eq!(len, written, "v1 EncodedLength disagreed with the encoder");
    Ok(buf)
}

fn encode_v0() -> Result<Vec<u8>, Box<dyn std::error::Error>> {
    let len = enc0::L3BookEncodedLength::new()
        .bids_ragged(BIDS.len() as u16, |b| {
            for lvl in BIDS {
                b.add()?.orders(|o| {
                    for ord in lvl.orders { o.add()?.order_id(ord.id.len())?; }
                    Ok(())
                })?;
            }
            Ok(())
        })?
        .asks_ragged(ASKS.len() as u16, |b| {
            for lvl in ASKS {
                b.add()?.ask_orders(|o| {
                    for ord in lvl.orders { o.add()?.order_id(ord.id.len())?; }
                    Ok(())
                })?;
            }
            Ok(())
        })?
        .symbol(SYMBOL.len())?
        .encoded_length_with_header();
    let mut buf = vec![0u8; len];
    let written = enc0::L3BookEncoder::try_wrap_and_apply_header(&mut buf, 0)?
        .fixed(&enc0::L3BookFixedFields { timestamp: TIMESTAMP, sequence: SEQUENCE })
        .bids(BIDS.len() as u16, |g| {
            for lvl in BIDS {
                g.add(|mut entry| {
                    entry.price(lvl.price).qty(lvl.qty);
                    entry.orders(lvl.orders.len() as u16, |o| {
                        for ord in lvl.orders {
                            o.add(|mut e| { e.order_qty(ord.qty); e.order_id(ord.id) })?;
                        }
                        Ok(())
                    })
                })?;
            }
            Ok(())
        })?
        .asks(ASKS.len() as u16, |g| {
            for lvl in ASKS {
                g.add(|mut entry| {
                    entry.price(lvl.price).qty(lvl.qty);
                    entry.ask_orders(lvl.orders.len() as u16, |o| {
                        for ord in lvl.orders {
                            o.add(|mut e| { e.order_qty(ord.qty); e.order_id(ord.id) })?;
                        }
                        Ok(())
                    })
                })?;
            }
            Ok(())
        })?
        .symbol(SYMBOL)?
        .encoded_length_with_header();
    assert_eq!(len, written, "v0 EncodedLength disagreed with the encoder");
    Ok(buf)
}

fn ergo_wire(version: u16) -> Result<Vec<u8>, Box<dyn std::error::Error>> {
    match version {
        0 => encode_v0(),
        1 => encode_v1(),
        2 => encode_v2(),
        _ => encode_v3(),
    }
}
"#;

#[test]
#[allow(clippy::too_many_lines)]
fn versioned_l3_dense_nested_book_is_byte_identical_to_sbe_tool() {
    run(
        "dual_vl3_encode",
        r#"
        use tool::{Encoder, WriteBuf, message_header_codec};
        use tool::l3_book_codec::{
            L3BookEncoder as ToolEnc,
            encoder::{
                AllocationsEncoder as ToolAllocs, AskAllocationsEncoder as ToolAskAllocs,
                AskLegsEncoder as ToolAskLegs, AskOrdersEncoder as ToolAskOrders,
                AskStatsEncoder as ToolAskStats, AsksEncoder as ToolAsks,
                AuditEncoder as ToolAudit, BidsEncoder as ToolBids, LegsEncoder as ToolLegs,
                OrdersEncoder as ToolOrders, StatsEncoder as ToolStats,
            },
        };

        let ergo_bytes = encode_v3()?;

        // sbe-tool writes into a buffer sized by ergo-sbe's EncodedLength; if
        // the two disagree on length the frame comparison says so directly.
        let mut tbuf = vec![0u8; ergo_bytes.len()];
        let mut t = ToolEnc::default()
            .wrap(WriteBuf::new(&mut tbuf), message_header_codec::ENCODED_LENGTH);
        t = t.header(0).parent().unwrap();
        t.timestamp(TIMESTAMP);
        t.sequence(SEQUENCE);
        t.epoch(EPOCH);
        t.flags(FLAGS);

        // `bids_encoder` / `asks_encoder` differ only in name, so the macro is
        // instantiated twice rather than made generic over the parent type.
        let mut bids = ToolBids::default();
        bids = t.bids_encoder(BIDS.len() as u16, bids);
        for lvl in BIDS {
            bids.advance().unwrap();
            bids.price(lvl.price);
            bids.qty(lvl.qty);
            bids.participant(lvl.participant);
            let mut orders = ToolOrders::default();
            orders = bids.orders_encoder(lvl.orders.len() as u16, orders);
            for ord in lvl.orders {
                orders.advance().unwrap();
                orders.order_qty(ord.qty);
                let mut allocs = ToolAllocs::default();
                allocs = orders.allocations_encoder(ord.allocations.len() as u16, allocs);
                for al in ord.allocations {
                    allocs.advance().unwrap();
                    allocs.alloc_qty(al.qty);
                    let mut legs = ToolLegs::default();
                    legs = allocs.legs_encoder(al.legs.len() as u16, legs);
                    for leg in al.legs {
                        legs.advance().unwrap();
                        legs.leg_qty(leg.qty);
                        legs.leg_ref(utf8(leg.reference));
                    }
                    allocs = legs.parent().unwrap();
                }
                orders = allocs.parent().unwrap();
                orders.order_id(utf8(ord.id));
                orders.trader_id(utf8(ord.trader));
            }
            bids = orders.parent().unwrap();
            let mut stats = ToolStats::default();
            stats = bids.stats_encoder(lvl.stats.len() as u16, stats);
            for st in lvl.stats {
                stats.advance().unwrap();
                stats.fill_count(st.fills);
                stats.fill_qty(st.qty);
            }
            bids = stats.parent().unwrap();
            bids.venue(utf8(lvl.venue));
        }
        t = bids.parent().unwrap();

        let mut asks = ToolAsks::default();
        asks = t.asks_encoder(ASKS.len() as u16, asks);
        for lvl in ASKS {
            asks.advance().unwrap();
            asks.price(lvl.price);
            asks.qty(lvl.qty);
            asks.participant(lvl.participant);
            let mut orders = ToolAskOrders::default();
            orders = asks.ask_orders_encoder(lvl.orders.len() as u16, orders);
            for ord in lvl.orders {
                orders.advance().unwrap();
                orders.order_qty(ord.qty);
                let mut allocs = ToolAskAllocs::default();
                allocs = orders.ask_allocations_encoder(ord.allocations.len() as u16, allocs);
                for al in ord.allocations {
                    allocs.advance().unwrap();
                    allocs.alloc_qty(al.qty);
                    let mut legs = ToolAskLegs::default();
                    legs = allocs.ask_legs_encoder(al.legs.len() as u16, legs);
                    for leg in al.legs {
                        legs.advance().unwrap();
                        legs.leg_qty(leg.qty);
                        legs.leg_ref(utf8(leg.reference));
                    }
                    allocs = legs.parent().unwrap();
                }
                orders = allocs.parent().unwrap();
                orders.order_id(utf8(ord.id));
                orders.trader_id(utf8(ord.trader));
            }
            asks = orders.parent().unwrap();
            let mut stats = ToolAskStats::default();
            stats = asks.ask_stats_encoder(lvl.stats.len() as u16, stats);
            for st in lvl.stats {
                stats.advance().unwrap();
                stats.fill_count(st.fills);
                stats.fill_qty(st.qty);
            }
            asks = stats.parent().unwrap();
            asks.venue(utf8(lvl.venue));
        }
        t = asks.parent().unwrap();

        let mut audit = ToolAudit::default();
        audit = t.audit_encoder(AUDIT.len() as u16, audit);
        for row in AUDIT {
            audit.advance().unwrap();
            audit.ts(row.ts);
            audit.code(row.code);
        }
        t = audit.parent().unwrap();

        t.symbol(utf8(SYMBOL));
        t.source(utf8(SOURCE));
        t.checksum(utf8(CHECKSUM));
        t.note(utf8(NOTE));
        let tl = t.get_limit();

        assert_frames_eq("versioned_l3 dense v3", &ergo_bytes, &tbuf[..tl]);
        println!("PASS: versioned_l3_dense_nested_book_is_byte_identical_to_sbe_tool");
        "#,
    );
}

#[test]
#[allow(clippy::too_many_lines)]
fn versioned_l3_sbe_tool_ordered_decode_reads_every_acting_version() {
    run(
        "dual_vl3_decode",
        r#"
        use tool::{Decoder, ReadBuf, message_header_codec};
        use tool::l3_book_codec::L3BookDecoder as ToolDec;

        // Walk one level group strictly in wire order. `bids` and `asks` are
        // separate generated types, so this is a macro rather than a function;
        // `version` and `wire` are passed in because macro_rules locals are
        // hygienic.
        macro_rules! walk_levels {
            (
                $start:expr, $levels:expr, $label:expr, $version:expr, $wire:expr,
                $orders:ident, $allocations:ident, $legs:ident, $stats:ident
            ) => {{
                let version: u16 = $version;
                let wire: &[u8] = $wire;
                let mut group = $start;
                assert_eq!(group.count() as usize, ($levels).len(), "{} count", $label);
                for (i, lvl) in ($levels).iter().enumerate() {
                    assert_eq!(group.advance().unwrap(), Some(i));
                    assert_eq!(group.price(), lvl.price, "{}[{i}].price", $label);
                    assert_eq!(group.qty(), lvl.qty, "{}[{i}].qty", $label);
                    if version >= 1 {
                        assert_eq!(
                            group.participant(), lvl.participant, "{}[{i}].participant", $label
                        );
                    }

                    let mut orders = group.$orders();
                    assert_eq!(
                        orders.count() as usize, lvl.orders.len(), "{}[{i}].orders count", $label
                    );
                    for (j, ord) in lvl.orders.iter().enumerate() {
                        assert_eq!(orders.advance().unwrap(), Some(j));
                        assert_eq!(orders.order_qty(), ord.qty, "{}[{i}].orders[{j}].qty", $label);
                        if version >= 2 {
                            let mut allocs = orders.$allocations().unwrap();
                            assert_eq!(
                                allocs.count() as usize,
                                ord.allocations.len(),
                                "{}[{i}].orders[{j}].allocations count",
                                $label
                            );
                            for (k, al) in ord.allocations.iter().enumerate() {
                                assert_eq!(allocs.advance().unwrap(), Some(k));
                                assert_eq!(allocs.alloc_qty(), al.qty);
                                if version >= 3 {
                                    let mut legs = allocs.$legs().unwrap();
                                    assert_eq!(legs.count() as usize, al.legs.len());
                                    for (l, leg) in al.legs.iter().enumerate() {
                                        assert_eq!(legs.advance().unwrap(), Some(l));
                                        assert_eq!(legs.leg_qty(), leg.qty);
                                        let c = legs.leg_ref_decoder();
                                        assert_eq!(&wire[c.0..c.0 + c.1], leg.reference);
                                    }
                                    allocs = legs.parent().unwrap();
                                }
                            }
                            orders = allocs.parent().unwrap();
                        }
                        let c = orders.order_id_decoder();
                        assert_eq!(&wire[c.0..c.0 + c.1], ord.id, "{}[{i}].orders[{j}].id", $label);
                        if version >= 1 {
                            let c = orders.trader_id_decoder();
                            assert_eq!(&wire[c.0..c.0 + c.1], ord.trader);
                        }
                    }
                    group = orders.parent().unwrap();

                    if version >= 2 {
                        let mut stats = group.$stats().unwrap();
                        assert_eq!(stats.count() as usize, lvl.stats.len());
                        for (s, st) in lvl.stats.iter().enumerate() {
                            assert_eq!(stats.advance().unwrap(), Some(s));
                            assert_eq!(stats.fill_count(), st.fills);
                            assert_eq!(stats.fill_qty(), st.qty);
                        }
                        group = stats.parent().unwrap();
                    }
                    if version >= 1 {
                        let c = group.venue_decoder();
                        assert_eq!(&wire[c.0..c.0 + c.1], lvl.venue, "{}[{i}].venue", $label);
                    }
                }
                group.parent().unwrap()
            }};
        }

        for version in 0u16..=3 {
            let wire = ergo_wire(version)?;
            let block_length = u16::from_le_bytes(wire[0..2].try_into().unwrap());
            let wire_version = u16::from_le_bytes(wire[6..8].try_into().unwrap());
            assert_eq!(wire_version, version, "ergo-sbe stamped the wrong version");

            let mut dec = ToolDec::default().wrap(
                ReadBuf::new(&wire),
                message_header_codec::ENCODED_LENGTH,
                block_length,
                wire_version,
            );
            assert_eq!(dec.timestamp(), TIMESTAMP);
            assert_eq!(dec.sequence(), SEQUENCE);
            if version >= 1 {
                assert_eq!(dec.epoch(), EPOCH);
            }
            if version >= 3 {
                assert_eq!(dec.flags(), FLAGS);
            }

            dec = walk_levels!(
                dec.bids_decoder(), BIDS, "bids", version, &wire,
                orders_decoder, allocations_decoder, legs_decoder, stats_decoder
            );
            dec = walk_levels!(
                dec.asks_decoder(), ASKS, "asks", version, &wire,
                ask_orders_decoder, ask_allocations_decoder, ask_legs_decoder,
                ask_stats_decoder
            );

            if version >= 2 {
                let mut audit = dec.audit_decoder().unwrap();
                assert_eq!(audit.count() as usize, AUDIT.len());
                for (i, row) in AUDIT.iter().enumerate() {
                    assert_eq!(audit.advance().unwrap(), Some(i));
                    assert_eq!(audit.ts(), row.ts);
                    assert_eq!(audit.code(), row.code);
                }
                dec = audit.parent().unwrap();
            }

            let c = dec.symbol_decoder();
            assert_eq!(&wire[c.0..c.0 + c.1], SYMBOL, "v{version} symbol");
            if version >= 1 {
                let c = dec.source_decoder();
                assert_eq!(&wire[c.0..c.0 + c.1], SOURCE, "v{version} source");
            }
            if version >= 2 {
                let c = dec.checksum_decoder();
                assert_eq!(&wire[c.0..c.0 + c.1], CHECKSUM, "v{version} checksum");
            }
            if version >= 3 {
                let c = dec.note_decoder();
                assert_eq!(&wire[c.0..c.0 + c.1], NOTE, "v{version} note");
            }
            // sbe-tool's limit is the end of the body; the frame adds the header.
            assert_eq!(
                dec.get_limit(),
                wire.len(),
                "v{version}: sbe-tool consumed a different number of bytes"
            );
        }
        println!("PASS: versioned_l3_sbe_tool_ordered_decode_reads_every_acting_version");
        "#,
    );
}
