[workspace]
resolver = "3"
members = ["aeron-bench", "aeron-driver", "engine", "md", "persist-client", "persist-server", "schema"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.98.1"
license = "Apache-2.0"
publish = false

[workspace.dependencies]
ergo-sbe = { path = "../../sbe" }
persist-client = { path = "persist-client" }
schema = { path = "schema" }
log = "0.4"
mimalloc = "0.1.52"
rusteron-archive = { version = "0.2.7", features = ["static", "multi-threaded"] }

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
unwrap_used = "deny"

[profile.release]
debug = "line-tables-only"
