[workspace]
resolver = "3"
members = ["persist", "recorder"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.98.1"
license = "Apache-2.0"
publish = false

[workspace.dependencies]
ergo-sbe = { path = "../../sbe" }

[workspace.lints.rust]
unsafe_code = "deny"

[workspace.lints.clippy]
all = { level = "deny", priority = -1 }
unwrap_used = "deny"

[profile.release]
debug = "line-tables-only"
