//! RFQ protocol codecs — generated from protocol-codecs.xml (schema 101).
//!
//! The `rfq_codec` module is generated by `build.rs` into `OUT_DIR`.

#[allow(
    dead_code,
    unused_imports,
    unused_variables,
    unused_mut,
    unused_comparisons,
    unused_assignments,
    non_camel_case_types,
    non_snake_case,
    unexpected_cfgs,
    clippy::all
)]
pub mod rfq_codec {
    #![allow(
        dead_code,
        unused_imports,
        unused_variables,
        unused_mut,
        unused_comparisons,
        unused_assignments,
        non_camel_case_types,
        non_snake_case,
        unexpected_cfgs,
        clippy::all
    )]
    include!(concat!(env!("OUT_DIR"), "/rfq_codec.rs"));
}
