[workspace]
members = ["sbe"]
exclude = ["samples"]
resolver = "3"

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
license = "Apache-2.0"
repository = "https://github.com/mimran1980/ErgoSBE"
homepage = "https://github.com/mimran1980/ErgoSBE"
authors = ["Mohammed Imran"]

[workspace.lints.rust]
unsafe_code = "deny"
missing_docs = "warn"

[workspace.lints.clippy]
all = "warn"
pedantic = "warn"
nursery = "warn"
unwrap_used = "warn"
expect_used = "warn"
panic = "warn"
