//! L3 order book codecs — generated from schemas/l3-book.xml.
//! Demonstrates nested repeating groups with domain-type converters.

#[allow(dead_code, unused_imports, non_camel_case_types, non_snake_case, clippy::all)]
mod l3_codec {
    include!(concat!(env!("OUT_DIR"), "/l3_codec.rs"));
}
pub use l3_codec::*;
use l3_codec::Decimal as SbeDecimal;

/// Exact header-inclusive encoded length of an L3 book for the given ragged
/// bids/asks + symbol, computed up-front via the staged `L3BookEncodedLength`.
/// Uses the schema-specific ragged builder wrappers — field-named methods,
/// zero user-defined constants.
pub fn book_encoded_length(
    bids: &[(rust_decimal::Decimal, rust_decimal::Decimal, &[(u64, rust_decimal::Decimal)])],
    asks: &[(rust_decimal::Decimal, rust_decimal::Decimal, &[(u64, rust_decimal::Decimal)])],
    symbol: &[u8],
) -> Result<usize, sbe_rt::EncodeError> {
    let after_bids = L3BookEncodedLength::new().bids_ragged(bids.len() as u16, |g| {
        for (_, _, orders) in bids {
            g.add()?.orders(|og| { og.uniform(orders.len())?; Ok(()) })?;
        }
        Ok(())
    })?;
    let after_asks = after_bids.asks_ragged(asks.len() as u16, |g| {
        for (_, _, orders) in asks {
            g.add()?.orders(|og| { og.uniform(orders.len())?; Ok(()) })?;
        }
        Ok(())
    })?;
    let complete = after_asks.symbol(symbol.len())?;
    Ok(complete.encoded_length_with_header())
}

// ── L3BookVarData ────────────────────────────────────────────────────────
// VarData orders are ragged at two levels: each order carries a var-data
// `order_id` of differing length. Uses the staged builder with schema-specific
// ragged wrapper types (field-named `order_id(len)` methods, zero constants).

/// Exact header-inclusive encoded length of an L3BookVarData book, computed
/// via the staged `L3BookVarDataEncodedLength` builder (nested-ragged).
pub fn vardata_book_encoded_length(
    bids: &[(rust_decimal::Decimal, rust_decimal::Decimal, &[(rust_decimal::Decimal, &[u8])])],
    asks: &[(rust_decimal::Decimal, rust_decimal::Decimal, &[(rust_decimal::Decimal, &[u8])])],
    symbol: &[u8],
) -> Result<usize, sbe_rt::EncodeError> {
    let after_bids = L3BookVarDataEncodedLength::new().bids_ragged(bids.len() as u16, |g| {
        for (_, _, orders) in bids {
            g.add()?.orders(|og| {
                for (_, order_id) in *orders {
                    og.add()?.order_id(order_id.len())?;
                }
                Ok(())
            })?;
        }
        Ok(())
    })?;
    let after_asks = after_bids.asks_ragged(asks.len() as u16, |g| {
        for (_, _, orders) in asks {
            g.add()?.orders(|og| {
                for (_, order_id) in *orders {
                    og.add()?.order_id(order_id.len())?;
                }
                Ok(())
            })?;
        }
        Ok(())
    })?;
    let complete = after_asks.symbol(symbol.len())?;
    Ok(complete.encoded_length_with_header())
}

/// Encode an L3 order book into `buf`. Returns the header-inclusive encoded length.
///
/// Uses known-size group construction — counts are known from slice lengths,
/// so no back-patching is needed. All numeric fields use `rust_decimal::Decimal`
/// and the timestamp uses `chrono::DateTime<Utc>` via the concrete converter
/// accessors generated by the `with_domain_type` configuration.
pub fn encode_book(
    buf: &mut [u8],
    bids: &[(rust_decimal::Decimal, rust_decimal::Decimal, &[(u64, rust_decimal::Decimal)])],
    asks: &[(rust_decimal::Decimal, rust_decimal::Decimal, &[(u64, rust_decimal::Decimal)])],
    symbol: &[u8],
) -> Result<usize, sbe_rt::EncodeError> {
    let complete = L3BookEncoder::try_wrap_and_apply_header(buf, 0)?
        .fixed(&L3BookFixedFields {
            exchange_timestamp: 1_720_000_000_000_000_000u64,
            sequence: 42,
            is_active: BooleanType::True,
        })
        .bids(bids.len() as u16, |g| {
            for (price, size, orders) in bids {
                g.add(|e| {
                    e.price(*price).size(*size);
                    e.orders(orders.len() as u16, |og| {
                        for (oid, qty) in *orders {
                            let raw_qty = SbeDecimal::new(qty.mantissa() as i64, -(qty.scale() as i8));
                            og.add_struct(&L3BookBidsOrdersEntry {
                                order_id: *oid,
                                quantity: raw_qty,
                            })?;
                        }
                        Ok(())
                    })?;
                    Ok(())
                })?;
            }
            Ok(())
        })?
        .asks(asks.len() as u16, |g| {
            for (price, size, orders) in asks {
                g.add(|e| {
                    e.price(*price).size(*size);
                    e.orders(orders.len() as u16, |og| {
                        for (oid, qty) in *orders {
                            let raw_qty = SbeDecimal::new(qty.mantissa() as i64, -(qty.scale() as i8));
                            og.add_struct(&L3BookAsksOrdersEntry {
                                order_id: *oid,
                                quantity: raw_qty,
                            })?;
                        }
                        Ok(())
                    })?;
                    Ok(())
                })?;
            }
            Ok(())
        })?
        .symbol(symbol)?;
    Ok(complete.encoded_length_with_header())
}
