//! L3 order book codecs — generated from schemas/l3-book.xml.
//! Demonstrates nested repeating groups with domain-type converters.

#[allow(dead_code, unused_imports, unused_variables, clippy::all)]
mod l3_codec {
    include!(concat!(env!("OUT_DIR"), "/l3_codec.rs"));
}
pub use l3_codec::*;

/// Encode an L3 order book into `buf`. Returns the header-inclusive encoded length.
///
/// Uses known-size group construction — counts are known from slice lengths,
/// so no back-patching is needed. All numeric fields use `rust_decimal::Decimal`
/// and the timestamp uses `chrono::DateTime<Utc>` via the concrete converter
/// accessors generated by the `with_domain_type` configuration.
pub fn encode_book(
    buf: &mut [u8],
    bids: &[(rust_decimal::Decimal, rust_decimal::Decimal, &[(u64, rust_decimal::Decimal)])],
    asks: &[(rust_decimal::Decimal, rust_decimal::Decimal, &[(u64, rust_decimal::Decimal)])],
    symbol: &[u8],
) -> Result<usize, sbe_rt::EncodeError> {
    let complete = L3BookEncoder::try_wrap_and_apply_header(buf, 0)?
        .fixed(&L3BookFixedFields {
            exchange_timestamp: 1_720_000_000_000_000_000u64,
            sequence: 42,
            is_active: BooleanType::True,
        })
        .bids(bids.len() as u16, |g| {
            for (price, size, orders) in bids {
                g.add(|e| {
                    e.price(*price).size(*size);
                    e.orders(orders.len() as u16, |og| {
                        for (oid, qty) in *orders {
                            let raw_qty = Decimal::new(qty.mantissa() as i64, -(qty.scale() as i8));
                            og.add_struct(&L3BookBidsOrdersEntry {
                                order_id: *oid,
                                quantity: raw_qty,
                            })?;
                        }
                        Ok(())
                    })?;
                    Ok(())
                })?;
            }
            Ok(())
        })?
        .asks(asks.len() as u16, |g| {
            for (price, size, orders) in asks {
                g.add(|e| {
                    e.price(*price).size(*size);
                    e.orders(orders.len() as u16, |og| {
                        for (oid, qty) in *orders {
                            let raw_qty = Decimal::new(qty.mantissa() as i64, -(qty.scale() as i8));
                            og.add_struct(&L3BookAsksOrdersEntry {
                                order_id: *oid,
                                quantity: raw_qty,
                            })?;
                        }
                        Ok(())
                    })?;
                    Ok(())
                })?;
            }
            Ok(())
        })?
        .symbol(symbol)?;
    Ok(complete.encoded_length_with_header())
}
