//! L3 order book codecs — generated from schemas/l3-book.xml.
//! Demonstrates nested repeating groups with domain-type converters.

#[allow(dead_code, unused_imports, unused_variables, clippy::all)]
mod l3_codec {
    include!(concat!(env!("OUT_DIR"), "/l3_codec.rs"));
}
pub use l3_codec::*;

/// Nested-orders group wire layout (structural constants from
/// `schemas/l3-book.xml`, not buffer guesses):
/// - dimension prefix: `u32` count = 4 bytes
/// - entry block: `u64 order_id` (8) + `Decimal` mantissa/exponent (9) = 17 bytes
// TODO: these manual group dim/block constants MUST come from the generated
// EncodedLength API (the staged builder should expose nested-group dim/block),
// not be hardcoded here. See CLAUDE.md "Buffer sizing" hard rule.
const ORDERS_DIM: usize = 4;
const ORDER_BLOCK: usize = 17;

/// Exact header-inclusive encoded length of an L3 book for the given ragged
/// bids/asks + symbol, computed up-front via the staged `L3BookEncodedLength`.
/// Allocate the encode buffer to exactly this length — no oversized buffer.
pub fn book_encoded_length(
    bids: &[(rust_decimal::Decimal, rust_decimal::Decimal, &[(u64, rust_decimal::Decimal)])],
    asks: &[(rust_decimal::Decimal, rust_decimal::Decimal, &[(u64, rust_decimal::Decimal)])],
    symbol: &[u8],
) -> Result<usize, sbe_rt::EncodeError> {
    let after_bids = L3BookEncodedLength::new().bids_ragged(bids.len() as u16, |g| {
        for (_, _, orders) in bids {
            g.add()?;
            g.group(ORDERS_DIM, ORDER_BLOCK, orders.len())?;
        }
        Ok(())
    })?;
    let after_asks = after_bids.asks_ragged(asks.len() as u16, |g| {
        for (_, _, orders) in asks {
            g.add()?;
            g.group(ORDERS_DIM, ORDER_BLOCK, orders.len())?;
        }
        Ok(())
    })?;
    let complete = after_asks.symbol(symbol.len())?;
    Ok(complete.encoded_length_with_header())
}

// ── L3BookVarData ────────────────────────────────────────────────────────
// VarData orders are ragged at two levels: each order carries a var-data
// `order_id` of differing length. The staged `L3BookVarDataEncodedLength`
// builder + `RaggedEntryBuilder::group_ragged` express this exactly.
// TODO: the group dim / entry block / var-data prefix passed to group_ragged
// and var_data should come from the generated EncodedLength API, not be
// hardcoded — see CLAUDE.md "Buffer sizing" hard rule.
const VD_ORDERS_DIM: usize = 4;   // groupSizeEncoding: u16 blockLength + u16 numInGroup
const VD_ORDER_BLOCK: usize = 9;  // quantity Decimal (order_id is var-data)
const VD_VAR_PREFIX: usize = 4;   // varAsciiEncoding length: u32

/// Exact header-inclusive encoded length of an L3BookVarData book, computed
/// via the staged `L3BookVarDataEncodedLength` builder (nested-ragged).
pub fn vardata_book_encoded_length(
    bids: &[(rust_decimal::Decimal, rust_decimal::Decimal, &[(rust_decimal::Decimal, &[u8])])],
    asks: &[(rust_decimal::Decimal, rust_decimal::Decimal, &[(rust_decimal::Decimal, &[u8])])],
    symbol: &[u8],
) -> Result<usize, sbe_rt::EncodeError> {
    let after_bids = L3BookVarDataEncodedLength::new().bids_ragged(bids.len() as u16, |g| {
        for (_, _, orders) in bids {
            g.add()?;
            g.group_ragged(VD_ORDERS_DIM, VD_ORDER_BLOCK, |og| {
                for (_, order_id) in *orders {
                    og.add()?;
                    og.var_data(VD_VAR_PREFIX, order_id.len())?;
                }
                Ok(())
            })?;
        }
        Ok(())
    })?;
    let after_asks = after_bids.asks_ragged(asks.len() as u16, |g| {
        for (_, _, orders) in asks {
            g.add()?;
            g.group_ragged(VD_ORDERS_DIM, VD_ORDER_BLOCK, |og| {
                for (_, order_id) in *orders {
                    og.add()?;
                    og.var_data(VD_VAR_PREFIX, order_id.len())?;
                }
                Ok(())
            })?;
        }
        Ok(())
    })?;
    let complete = after_asks.symbol(symbol.len())?;
    Ok(complete.encoded_length_with_header())
}

/// Encode an L3 order book into `buf`. Returns the header-inclusive encoded length.
///
/// Uses known-size group construction — counts are known from slice lengths,
/// so no back-patching is needed. All numeric fields use `rust_decimal::Decimal`
/// and the timestamp uses `chrono::DateTime<Utc>` via the concrete converter
/// accessors generated by the `with_domain_type` configuration.
pub fn encode_book(
    buf: &mut [u8],
    bids: &[(rust_decimal::Decimal, rust_decimal::Decimal, &[(u64, rust_decimal::Decimal)])],
    asks: &[(rust_decimal::Decimal, rust_decimal::Decimal, &[(u64, rust_decimal::Decimal)])],
    symbol: &[u8],
) -> Result<usize, sbe_rt::EncodeError> {
    let complete = L3BookEncoder::try_wrap_and_apply_header(buf, 0)?
        .fixed(&L3BookFixedFields {
            exchange_timestamp: 1_720_000_000_000_000_000u64,
            sequence: 42,
            is_active: BooleanType::True,
        })
        .bids(bids.len() as u16, |g| {
            for (price, size, orders) in bids {
                g.add(|e| {
                    e.price(*price).size(*size);
                    e.orders(orders.len() as u16, |og| {
                        for (oid, qty) in *orders {
                            let raw_qty = Decimal::new(qty.mantissa() as i64, -(qty.scale() as i8));
                            og.add_struct(&L3BookBidsOrdersEntry {
                                order_id: *oid,
                                quantity: raw_qty,
                            })?;
                        }
                        Ok(())
                    })?;
                    Ok(())
                })?;
            }
            Ok(())
        })?
        .asks(asks.len() as u16, |g| {
            for (price, size, orders) in asks {
                g.add(|e| {
                    e.price(*price).size(*size);
                    e.orders(orders.len() as u16, |og| {
                        for (oid, qty) in *orders {
                            let raw_qty = Decimal::new(qty.mantissa() as i64, -(qty.scale() as i8));
                            og.add_struct(&L3BookAsksOrdersEntry {
                                order_id: *oid,
                                quantity: raw_qty,
                            })?;
                        }
                        Ok(())
                    })?;
                    Ok(())
                })?;
            }
            Ok(())
        })?
        .symbol(symbol)?;
    Ok(complete.encoded_length_with_header())
}
