apiVersion: 1
datasources:
  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    isDefault: true
    jsonData:
      host: clickhouse
      port: 8123
      protocol: http
      username: lab
      defaultDatabase: market
    secureJsonData:
      password: lab
