# Bybit's feed handler, md-bybit, in region as1.
resources: [../base]
nameSuffix: -bybit
labels:
  - pairs: { exchange: bybit }
    includeSelectors: true
patches:
  - target: { kind: Deployment }
    patch: |-
      - { op: add, path: /spec/template/spec/nodeSelector, value: { topology.kubernetes.io/region: as1 } }
