[package]
name = "archive-agent"
description = "Registration/catalog owner + metrics for each producer pod"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
ergo-clickhouse-persist = { workspace = true, features = ["producer"] }
rusqlite = { workspace = true }
rusteron-client = { workspace = true }
