//! Exact Decimal adapters: wire SBE Decimal ↔ rust_decimal::Decimal.
//!
//! Implements the generated `TryFromSbe` trait for `rust_decimal::Decimal`,
//! providing exact, fallible, allocation-free conversion. Also provides a
//! scaled-integer adapter as a domain-mapping example.

use std::str::FromStr;

/// A wire SBE Decimal value: `mantissa × 10^exponent`.
/// Renamed from `TryFromSbe` to avoid clashing with the generated trait.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct WireDecimal {
    pub mantissa: i64,
    pub exponent: i8,
}

impl WireDecimal {
    pub const fn new(mantissa: i64, exponent: i8) -> Self {
        Self { mantissa, exponent }
    }
}

/// Errors returned by TryFromSbe conversion.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum DecimalConvertError {
    /// Scaling factor overflowed.
    Overflow,
    /// Non-zero digits would be discarded by rescaling.
    PrecisionLoss,
    /// Value outside the target range.
    OutOfRange,
}

impl core::fmt::Display for DecimalConvertError {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        match self {
            Self::Overflow => write!(f, "decimal overflow"),
            Self::PrecisionLoss => write!(f, "decimal precision loss"),
            Self::OutOfRange => write!(f, "decimal out of range"),
        }
    }
}

impl std::error::Error for DecimalConvertError {}

// ── TryFromSbe trait impl for rust_decimal::Decimal ───────────────────
// This impl lives here but is only compiled when the `normalized_app`
// module (generated by build.rs) is in scope. Tests and the binary
// include this module alongside normalized_app.
//
// Generated code never mentions rust_decimal.

/// Macro to implement the generated conversion traits for rust_decimal::Decimal
/// in any module that has `normalized_app` in scope.
#[macro_export]
macro_rules! impl_sbe_decimal_for_rust_decimal {
    () => {
        impl normalized_app::TryFromSbe<normalized_app::Decimal> for rust_decimal::Decimal {
            type Error = $crate::decimal::DecimalConvertError;

            fn try_from_sbe(wire: normalized_app::Decimal) -> Result<Self, Self::Error> {
                let mantissa = wire.mantissa();
                let exponent = wire.exponent();
                if exponent <= 0 {
                    let scale = u32::from(exponent.unsigned_abs());
                    rust_decimal::Decimal::try_new(mantissa, scale)
                        .map_err(|_| $crate::decimal::DecimalConvertError::Overflow)
                } else {
                    let factor = 10i128
                        .checked_pow(u32::from(exponent.unsigned_abs()))
                        .ok_or($crate::decimal::DecimalConvertError::Overflow)?;
                    let scaled = i128::from(mantissa)
                        .checked_mul(factor)
                        .ok_or($crate::decimal::DecimalConvertError::Overflow)?;
                    rust_decimal::Decimal::try_from_i128_with_scale(scaled, 0)
                        .map_err(|_| $crate::decimal::DecimalConvertError::Overflow)
                }
            }
        }

        impl normalized_app::TryToSbe<normalized_app::Decimal> for rust_decimal::Decimal {
            type Error = $crate::decimal::DecimalConvertError;

            fn try_to_sbe(&self) -> Result<normalized_app::Decimal, Self::Error> {
                let mantissa: i128 = self.mantissa();
                let scale = self.scale();
                if scale > 127 {
                    return Err($crate::decimal::DecimalConvertError::Overflow);
                }
                let mantissa: i64 = mantissa
                    .try_into()
                    .map_err(|_| $crate::decimal::DecimalConvertError::Overflow)?;
                let exponent: i8 = -(scale as i8);
                Ok(normalized_app::Decimal::new(mantissa, exponent))
            }
        }
    };
}

// ── ClickHouse Decimal(38,18) adapter ─────────────────────────────────

/// Maximum value for Decimal(38,18): (10^38 - 1).
const DECIMAL_38_18_MAX: i128 = 99999999999999999999999999999999999999;
const DECIMAL_38_18_MIN: i128 = -DECIMAL_38_18_MAX;

/// Convert a wire (mantissa, exponent) to ClickHouse Decimal(38,18) scaled integer.
///
/// `scaled = mantissa × 10^(exponent + 18)`. Rejects overflow and non-zero
/// precision loss.
pub fn to_clickhouse_decimal(mantissa: i64, exponent: i8) -> Result<i128, DecimalConvertError> {
    let scale_diff = i32::from(exponent) + 18;

    if scale_diff >= 0 {
        let factor = ten_pow(scale_diff as u32).ok_or(DecimalConvertError::Overflow)?;
        let scaled = (mantissa as i128)
            .checked_mul(factor)
            .ok_or(DecimalConvertError::Overflow)?;
        check_range(scaled)?;
        Ok(scaled)
    } else {
        let divisor = ten_pow((-scale_diff) as u32).ok_or(DecimalConvertError::Overflow)?;
        let m = mantissa as i128;
        if m % divisor != 0 {
            return Err(DecimalConvertError::PrecisionLoss);
        }
        let scaled = m / divisor;
        check_range(scaled)?;
        Ok(scaled)
    }
}

fn check_range(scaled: i128) -> Result<(), DecimalConvertError> {
    if !(DECIMAL_38_18_MIN..=DECIMAL_38_18_MAX).contains(&scaled) {
        Err(DecimalConvertError::OutOfRange)
    } else {
        Ok(())
    }
}

fn ten_pow(n: u32) -> Option<i128> {
    if n > 38 {
        return None;
    }
    let mut result: i128 = 1;
    for _ in 0..n {
        result = result.checked_mul(10)?;
    }
    Some(result)
}

/// Parse a decimal string exactly using rust_decimal, returning (mantissa, exponent).
/// Invalid input returns an error — never silently converts to zero.
pub fn parse_decimal_exact(s: &str) -> Result<WireDecimal, DecimalConvertError> {
    let d = rust_decimal::Decimal::from_str(s).map_err(|_| DecimalConvertError::OutOfRange)?;
    let mantissa: i128 = d.mantissa();
    let scale = d.scale();
    if scale > 127 {
        return Err(DecimalConvertError::Overflow);
    }
    let mantissa: i64 = mantissa
        .try_into()
        .map_err(|_| DecimalConvertError::Overflow)?;
    Ok(WireDecimal::new(mantissa, -(scale as i8)))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn exact_conversion_no_scaling() -> Result<(), Box<dyn std::error::Error>> {
        let result = to_clickhouse_decimal(1_2345_6789_0123_4567i64, -18).unwrap();
        assert_eq!(result, 1_2345_6789_0123_4567i128);

        Ok(())
    }

    #[test]
    fn scale_up_mantissa() -> Result<(), Box<dyn std::error::Error>> {
        let result = to_clickhouse_decimal(100_000_000, -8).unwrap();
        assert_eq!(result, 1_000_000_000_000_000_000i128);

        Ok(())
    }

    #[test]
    fn scale_down_mantissa_exact() -> Result<(), Box<dyn std::error::Error>> {
        let result = to_clickhouse_decimal(12300, -20).unwrap();
        assert_eq!(result, 123);

        Ok(())
    }

    #[test]
    fn precision_loss_rejected() -> Result<(), Box<dyn std::error::Error>> {
        let err = to_clickhouse_decimal(123, -20).unwrap_err();
        assert!(matches!(err, DecimalConvertError::PrecisionLoss));

        Ok(())
    }

    #[test]
    fn exact_values_roundtrip() -> Result<(), Box<dyn std::error::Error>> {
        let cases = [
            (0, 0i8),
            (1, 0),
            (-1, 0),
            (12345, -2),
            (5_000_000, -2),
            (150, -2),
            (i64::MAX, 0),
            (1, -18),
        ];
        for (mantissa, exponent) in &cases {
            let result = to_clickhouse_decimal(*mantissa, *exponent);
            assert!(
                result.is_ok(),
                "failed: {mantissa} × 10^{exponent}: {:?}",
                result.err()
            );
        }

        Ok(())
    }

    #[test]
    fn overflow_rejected() -> Result<(), Box<dyn std::error::Error>> {
        let err = to_clickhouse_decimal(i64::MAX, 20).unwrap_err();
        assert!(matches!(err, DecimalConvertError::Overflow));

        Ok(())
    }

    #[test]
    fn parse_exact_valid() -> Result<(), Box<dyn std::error::Error>> {
        let wd = parse_decimal_exact("50000.00").unwrap();
        assert_eq!(wd.mantissa, 5000000);
        assert_eq!(wd.exponent, -2);

        Ok(())
    }

    #[test]
    fn parse_exact_invalid_rejected() -> Result<(), Box<dyn std::error::Error>> {
        assert!(parse_decimal_exact("not_a_number").is_err());

        Ok(())
    }

    #[test]
    fn parse_exact_small_value() -> Result<(), Box<dyn std::error::Error>> {
        let wd = parse_decimal_exact("0.0015").unwrap();
        assert_eq!(wd.mantissa, 15);
        assert_eq!(wd.exponent, -4);

        Ok(())
    }

    #[test]
    fn rust_decimal_sbe_roundtrip() -> Result<(), Box<dyn std::error::Error>> {
        // Test the try_into_sbe direction (mantissa/scale extraction).
        let d = rust_decimal::Decimal::new(5000000, 2); // 50000.00
        let mantissa: i128 = d.mantissa();
        let scale = d.scale();
        assert_eq!(mantissa, 5000000);
        assert_eq!(scale, 2);
        assert_eq!(-(scale as i8), -2);

        Ok(())
    }
}
