[package]
name = "ergosbe"
description = "Opinionated, idiomatic Rust code generation for Simple Binary Encoding."
keywords = ["sbe", "codegen", "binary", "protocol", "trading"]
categories = ["encoding", "parser-implementations", "development-tools"]
readme = "../../README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[lib]
path = "src/lib.rs"

[dev-dependencies]
roxmltree = "0.20"

[lints]
workspace = true
