//! Replaying the engine with no infrastructure: a deterministic synthetic
//! market as a frame log, and the engine run over it in simulation.
//!
//! The checked-in `tests/fixtures/engine-inbound.bin` is [`inbound`] of
//! [`Market::FIXTURE`]; `engine-outbound.golden` is [`run`] over it. Both are
//! regenerated by `just engine-fixtures` and checked by its `--check`.

use ergon_runtime::Error;
use ergon_runtime::clock::Nanos;
use ergon_runtime::frames::FrameLog;
use ergon_runtime::rt::sim::{Sim, SimConfig};
use lab::Streams;
use schema::market::sbe_rt::EncodeError;
use schema::market::{
    BookAction, BookDeltasDeltasEntry, BookDeltasEncoder, BookDeltasFixedFields,
    BookSnapshotAsksEntry, BookSnapshotBidsEntry, BookSnapshotEncoder, BookSnapshotFixedFields,
    Decimal9, InstrumentSpecEncoder, InstrumentSpecFixedFields, Side,
};

use crate::agent::Engine;

/// The registry a replay runs against: two venues in two regions, and this
/// region's engine and exchange. Its names never resolve (`.invalid`), so a
/// live test's subscriptions fail at once: a `.local` name takes the
/// resolver seconds on macOS, and the media driver resolves on its only
/// thread.
pub const STREAMS: &str = "\
domain: invalid
services:
  md-alpha: { port: 41001, region: r1, streams: { md: 101, tob: 102 } }
  md-beta: { port: 41002, region: r2, streams: { md: 103, tob: 104 } }
  engine-r1: { port: 41003, region: r1, streams: { signals: 105, orders: 106 } }
  exch-sim-r1: { port: 41004, region: r1, streams: { exec: 107 } }
kinds:
  md: { reliable: true }
  tob: { reliable: false }
  signals: { reliable: true }
  orders: { reliable: true }
  exec: { reliable: true }
";

/// The replay's region.
pub const REGION: &str = "r1";

const VENUES: [(&str, &[u8]); 2] = [("md-alpha", b"ALPHA"), ("md-beta", b"BETA")];
const SECOND: i64 = 1_000_000_000;
const T0: i64 = 1_767_225_600_000_000_000;
/// One cent, as a `Decimal9` mantissa.
const CENT: i64 = 10_000_000;

/// A synthetic market: a trending random walk per venue.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Market {
    /// Seeds the walk.
    pub seed: u64,
    /// Seconds of book changes, one a second per venue.
    pub seconds: u32,
    /// Repeat a venue's last sequence every this many changes: a gap to a
    /// monotonic venue. Zero for none.
    pub repeat_every: u32,
}

impl Market {
    /// The checked-in fixture: five minutes, enough EMA crosses to trade.
    pub const FIXTURE: Self = Self {
        seed: 0x5eed,
        seconds: 300,
        repeat_every: 0,
    };
}

const fn xorshift(mut x: u64) -> u64 {
    x ^= x << 13;
    x ^= x >> 7;
    x ^= x << 17;
    x
}

/// `market` as a frame log of `md-<venue>/md` streams: an instrument spec
/// and a snapshot at the start, one book change a second, and a snapshot
/// every 30 s, each stamped with its publish time.
#[must_use]
pub fn inbound(market: &Market) -> Vec<u8> {
    let mut log = FrameLog::new();
    let streams = VENUES.map(|(service, _)| log.stream(&format!("{service}/md")));
    let mut rng = market.seed | 1;
    let mut mid = 6_000_000 * CENT;
    let mut seq = [1_000_u64; 2];
    let mut last = [(0_i64, 0_i64); 2];
    for (v, (_, venue)) in VENUES.iter().enumerate() {
        log.push(streams[v], Nanos(T0), &spec(venue, T0));
    }
    for second in 0..=market.seconds {
        let ts = T0 + i64::from(second) * SECOND;
        // A trend that turns every 90 s, and noise around it.
        rng = xorshift(rng);
        let up = (second / 90) % 2 == 0;
        let noise = i64::try_from(rng % 2_001).unwrap_or(0) - 1_000;
        mid += if up { 400 } else { -400 } * CENT / 100 + noise * CENT / 100;
        for (v, (_, venue)) in VENUES.iter().enumerate() {
            let venue_mid = mid + i64::try_from(v).unwrap_or(0) * 7 * CENT;
            let (bid, ask) = (venue_mid - 50 * CENT, venue_mid + 50 * CENT);
            let ts = ts + i64::try_from(v).unwrap_or(0) * 1_000;
            let repeat = market.repeat_every > 0 && second % market.repeat_every == 0;
            if !repeat {
                seq[v] += 1;
            }
            let frame = if second % 30 == 0 {
                snapshot(venue, ts, seq[v], bid, ask)
            } else {
                deltas(venue, ts, seq[v], last[v], (bid, ask))
            };
            log.push(streams[v], Nanos(ts), &frame);
            last[v] = (bid, ask);
        }
    }
    log.to_bytes()
}

fn spec(venue: &[u8], ts: i64) -> Vec<u8> {
    let len = InstrumentSpecEncoder::compute_length_with_header(7, venue.len(), 3, 4);
    let mut buf = vec![0; len];
    let encoded: Result<usize, EncodeError> = (|| {
        Ok(InstrumentSpecEncoder::wrap_and_apply_header(&mut buf, 0)
            .fixed(&InstrumentSpecFixedFields {
                ts_event: ts.cast_unsigned(),
                multiplier: Decimal9::new(1_000_000_000),
                inverse: 0,
            })
            .symbol(b"BTCUSDT")?
            .venue(venue)?
            .base(b"BTC")?
            .quote(b"USDT")?
            .encoded_length_with_header())
    })();
    debug_assert_eq!(encoded.ok(), Some(len));
    buf
}

fn snapshot(venue: &[u8], ts: i64, seq: u64, bid: i64, ask: i64) -> Vec<u8> {
    let len = BookSnapshotEncoder::compute_length_with_header(5, 5, 7, venue.len());
    let mut buf = vec![0; len];
    let size = Decimal9::new(2_000_000_000);
    let encoded: Result<usize, EncodeError> = (|| {
        Ok(BookSnapshotEncoder::wrap_and_apply_header(&mut buf, 0)
            .fixed(&BookSnapshotFixedFields {
                ts_event: (ts - 2_000_000).cast_unsigned(),
                ts_init: ts.cast_unsigned(),
                sequence: seq,
            })
            .bids(5, |g| {
                for k in 0..5 {
                    let price = Decimal9::new(bid - k * 10 * CENT);
                    g.add_struct(&BookSnapshotBidsEntry { price, size })?;
                }
                Ok(())
            })?
            .asks(5, |g| {
                for k in 0..5 {
                    let price = Decimal9::new(ask + k * 10 * CENT);
                    g.add_struct(&BookSnapshotAsksEntry { price, size })?;
                }
                Ok(())
            })?
            .symbol(b"BTCUSDT")?
            .venue(venue)?
            .encoded_length_with_header())
    })();
    debug_assert_eq!(encoded.ok(), Some(len));
    buf
}

/// The best level moves: delete the old best bid and ask, set the new ones.
fn deltas(venue: &[u8], ts: i64, seq: u64, old: (i64, i64), new: (i64, i64)) -> Vec<u8> {
    let size = Decimal9::new(1_000_000_000);
    let entry = |action, side, price| BookDeltasDeltasEntry {
        action,
        side,
        price: Decimal9::new(price),
        size,
    };
    let entries = [
        entry(BookAction::Delete, Side::Buy, old.0),
        entry(BookAction::Delete, Side::Sell, old.1),
        entry(BookAction::Add, Side::Buy, new.0),
        entry(BookAction::Add, Side::Sell, new.1),
    ];
    let len = BookDeltasEncoder::compute_length_with_header(entries.len(), 7, venue.len());
    let mut buf = vec![0; len];
    let encoded: Result<usize, EncodeError> = (|| {
        Ok(BookDeltasEncoder::wrap_and_apply_header(&mut buf, 0)
            .fixed(&BookDeltasFixedFields {
                ts_event: (ts - 2_000_000).cast_unsigned(),
                ts_init: ts.cast_unsigned(),
                sequence: seq,
            })
            .deltas(4, |g| {
                for e in &entries {
                    g.add_struct(e)?;
                }
                Ok(())
            })?
            .symbol(b"BTCUSDT")?
            .venue(venue)?
            .encoded_length_with_header())
    })();
    debug_assert_eq!(encoded.ok(), Some(len));
    buf
}

/// The engine of [`REGION`] over `inbound`, in simulation: what it
/// published, as a frame log.
///
/// # Errors
///
/// `inbound` is not a frame log, or the engine could not start.
pub fn run(inbound: Vec<u8>) -> Result<Vec<u8>, Error> {
    let config = SimConfig {
        region: REGION.into(),
        ..SimConfig::new()
    };
    let mut sim = Sim::new(config, vec![inbound])?;
    let mut engine = Engine::new(sim.ctx(), Streams::parse(STREAMS)?)?;
    sim.run(&mut engine)?;
    Ok(sim.ctx().captured().to_bytes())
}
