#!/usr/bin/env python3
"""Regenerate the codegen combination-matrix fixture schema.

`SHAPES` is the single source of truth for which field shapes the codegen
matrix covers. `sbe/tests/codegen_matrix_test.rs` recomputes the same cross
product and fails when the fixture falls behind, so adding a shape here is what
forces new coverage into existence.

    ./scripts/regenerate-codegen-matrix-fixture.py           # rewrite fixture
    ./scripts/regenerate-codegen-matrix-fixture.py --check   # fail on drift
"""

import pathlib
import sys

FIXTURE = (
    pathlib.Path(__file__).resolve().parent.parent
    / "sbe/tests/fixtures/schemas/codegen-matrix-schema.xml"
)

# (prefix, schema type ref, comment) — "mapped" shapes carry a selector that a
# domain type is configured for; "plain" shapes carry none.
SHAPES = [
    ("sDom",       "Scaled",    'semanticType="ScaledPrice"', "primitive scalar, domain-mapped"),
    ("sPlain",     "uint32",    "",                            "primitive scalar, unmapped"),
    ("sOptDom",    "OptScaled", 'semanticType="ScaledPrice"', "optional scalar, domain-mapped (domain not applied)"),
    ("sOptPlain",  "OptPlain",  "",                            "optional scalar, unmapped"),
    ("aDom",       "Tag",       'semanticType="TagText"',     "fixed array, domain-mapped (domain not applied)"),
    ("aPlain",     "TagPlain",  "",                            "fixed array, unmapped"),
    ("cDom",       "Money",     "",                            "composite, domain-mapped via NamedType"),
    ("cPlain",     "Pair",      "",                            "composite, unmapped"),
    ("eBool",      "BooleanType", "",                          "bool enum, required"),
    ("eBoolOpt",   "BooleanType", 'presence="optional"',      "bool enum, optional (field-level presence)"),
    ("eNorm",      "Model",     "",                            "non-bool enum"),
    ("setOpt",     "Opts",      "",                            "bitset"),
]

# sinceVersion values under test.
VERSIONS = [0, 1]


def cells():
    for prefix, ty, attrs, _c in SHAPES:
        for v in VERSIONS:
            yield (f"{prefix}V{v}", ty, attrs, v)


def fields(start_id, indent):
    out = []
    fid = start_id
    for prefix, ty, attrs, comment in SHAPES:
        out.append(f"{indent}<!-- {comment} -->")
        for v in VERSIONS:
            since = f' sinceVersion="{v}"' if v else ""
            a = f" {attrs}" if attrs else ""
            out.append(f'{indent}<field name="{prefix}V{v}" id="{fid}" type="{ty}"{a}{since}/>')
            fid += 1
    return out, fid


HEADER = '''<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!-- GENERATED by scripts/gen-codegen-matrix-fixture.py — do not hand-edit.

     Cross product of field shape x sinceVersion, repeated at three codegen
     locations: message level, group-entry level, and nested-group-entry level.
     `codegen::converter_impls` has separate message-level and group-entry
     loops, and the domain-DTO generator recurses separately for entry DTOs, so
     a cell proven at one location proves nothing about the others.

     Field naming is <shape>V<sinceVersion>; `codegen_matrix_test` recomputes
     this cross product and fails if a cell is missing here. -->
<sbe:messageSchema xmlns:sbe="http://fixprotocol.io/2016/sbe"
                   package="codegen_matrix"
                   id="204"
                   version="3"
                   semanticVersion="5.2"
                   description="Codegen combination matrix"
                   byteOrder="littleEndian">
    <types>
        <composite name="messageHeader" description="Message identifiers and length of message root">
            <type name="blockLength" primitiveType="uint16"/>
            <type name="templateId" primitiveType="uint16"/>
            <type name="schemaId" primitiveType="uint16"/>
            <type name="version" primitiveType="uint16"/>
        </composite>
        <composite name="groupSizeEncoding" description="Repeating group dimensions">
            <type name="blockLength" primitiveType="uint16"/>
            <type name="numInGroup" primitiveType="uint16"/>
        </composite>
        <composite name="varStringEncoding">
            <type name="length" primitiveType="uint32" maxValue="1073741824"/>
            <type name="varData" primitiveType="uint8" length="0" characterEncoding="UTF-8"/>
        </composite>

        <composite name="Money">
            <type name="mantissa" primitiveType="int64"/>
            <type name="exponent" primitiveType="int8"/>
        </composite>
        <composite name="Pair">
            <type name="lo" primitiveType="uint32"/>
            <type name="hi" primitiveType="uint32"/>
        </composite>

        <enum name="BooleanType" encodingType="uint8">
            <validValue name="F">0</validValue>
            <validValue name="T">1</validValue>
        </enum>
        <enum name="Model" encodingType="char">
            <validValue name="A">A</validValue>
            <validValue name="B">B</validValue>
        </enum>
        <set name="Opts" encodingType="uint8">
            <choice name="fast">0</choice>
            <choice name="safe">1</choice>
        </set>

        <type name="Scaled" primitiveType="int64"/>
        <type name="OptScaled" primitiveType="int64" presence="optional"/>
        <type name="OptPlain" primitiveType="int32" presence="optional"/>
        <type name="Tag" primitiveType="char" length="4"/>
        <type name="TagPlain" primitiveType="char" length="4"/>
    </types>
'''

FOOTER = "</sbe:messageSchema>\n"


def main():
    parts = [HEADER]

    # Message-level cells.
    msg_fields, nid = fields(1, " " * 8)
    parts.append('    <sbe:message name="Flat" id="1">\n')
    parts.append("\n".join(msg_fields) + "\n")
    parts.append('        <!-- constant: excluded from the DTO entirely -->\n')
    parts.append(f'        <field name="kConst" id="{nid}" type="Model" presence="constant" valueRef="Model.B"/>\n')
    nid += 1
    parts.append('        <data name="note" id="900" type="varStringEncoding"/>\n')
    parts.append("    </sbe:message>\n\n")

    # Group and nested-group cells.
    grp_fields, nid = fields(nid, " " * 12)
    nest_fields, nid = fields(nid, " " * 16)
    parts.append('    <sbe:message name="Nested" id="2">\n')
    parts.append('        <field name="seq" id="800" type="uint32"/>\n')
    parts.append('        <group name="rows" id="810" dimensionType="groupSizeEncoding">\n')
    parts.append("\n".join(grp_fields) + "\n")
    parts.append('            <group name="cells" id="820" dimensionType="groupSizeEncoding">\n')
    parts.append("\n".join(nest_fields) + "\n")
    parts.append("            </group>\n")
    parts.append('            <data name="rowNote" id="901" type="varStringEncoding"/>\n')
    parts.append("        </group>\n")
    parts.append("    </sbe:message>\n")

    parts.append(FOOTER)
    return "".join(parts)


if __name__ == "__main__":
    rendered = main()
    if "--check" in sys.argv:
        current = FIXTURE.read_text() if FIXTURE.exists() else ""
        if current != rendered:
            print(
                f"codegen matrix fixture: DRIFT — {FIXTURE} does not match "
                "SHAPES in this script.\nRun ./scripts/regenerate-codegen-matrix-fixture.py",
                file=sys.stderr,
            )
            sys.exit(1)
        print(f"codegen matrix fixture: PASS ({len(SHAPES)} shapes x {len(VERSIONS)} versions)")
    else:
        FIXTURE.write_text(rendered)
        print(f"codegen matrix fixture: wrote {FIXTURE}")
