//! Cluster SBE codecs — ErgoSBE-generated from Aeron schemas (OUT_DIR).
//!
//! - [`session`] — Aeron cluster session schema 111
//! - [`mark`]    — cluster mark schema
//! - [`rfq`]     — cookbook RFQ schema 101 from `schemas/protocol-codecs.xml`
//!
//! Generated by `build.rs` at compile time. The sbe-tool reference runtime
//! for benchmarks lives at `cluster/benches/reference_sbe/` (Criterion-private).

#[allow(
    dead_code,
    unused_imports,
    unused_variables,
    unused_mut,
    unused_comparisons,
    unused_assignments,
    non_camel_case_types,
    non_snake_case,
    unexpected_cfgs,
    clippy::all
)]
pub mod session {
    #![allow(
        dead_code,
        unused_imports,
        unused_variables,
        unused_mut,
        unused_comparisons,
        unused_assignments,
        non_camel_case_types,
        non_snake_case,
        unexpected_cfgs,
        clippy::all
    )]
    include!(concat!(env!("OUT_DIR"), "/session.rs"));
}

#[allow(
    dead_code,
    unused_imports,
    unused_variables,
    unused_mut,
    unused_comparisons,
    unused_assignments,
    non_camel_case_types,
    non_snake_case,
    unexpected_cfgs,
    clippy::all
)]
pub mod mark {
    #![allow(
        dead_code,
        unused_imports,
        unused_variables,
        unused_mut,
        unused_comparisons,
        unused_assignments,
        non_camel_case_types,
        non_snake_case,
        unexpected_cfgs,
        clippy::all
    )]
    include!(concat!(env!("OUT_DIR"), "/mark.rs"));
}

#[allow(
    dead_code,
    unused_imports,
    unused_variables,
    unused_mut,
    unused_comparisons,
    unused_assignments,
    non_camel_case_types,
    non_snake_case,
    unexpected_cfgs,
    clippy::all
)]
pub mod rfq {
    #![allow(
        dead_code,
        unused_imports,
        unused_variables,
        unused_mut,
        unused_comparisons,
        unused_assignments,
        non_camel_case_types,
        non_snake_case,
        unexpected_cfgs,
        clippy::all
    )]
    include!(concat!(env!("OUT_DIR"), "/rfq.rs"));
}

#[cfg(test)]
mod tests;
