//! Cluster SBE codecs — ergo-sbe-generated from Aeron schemas (OUT_DIR).
//!
//! - `session` — Aeron cluster session schema 111
//! - `mark`    — cluster mark schema
//!
#![allow(unused_unsafe)]
//! Generated by `build.rs` (`generate_to_out_dir`) at compile time. The
//! sbe-tool reference runtime for benchmarks lives at
//! `cluster/benches/reference_sbe/` (Criterion-private).

ergo_sbe::sbe_mod!(pub session);
ergo_sbe::sbe_mod!(pub mark);

#[cfg(test)]
mod tests;
