//! Cluster SBE codecs generated by sbe-tool 1.39.0.
//!
//! DO NOT HAND-EDIT files under `cluster_codecs/` or `cluster_codecs_mark/`.
//! Use `just generate-cluster-codecs` to regenerate.

pub mod cluster_codecs;
pub mod cluster_codecs_mark;
pub mod rfq_codecs;

// sbe-tool 1.39.0 omits `impl Writer for WriteBuf`; provided here so the
// generated `mod.rs` files stay pure generator output. See writer_impls.rs.
mod writer_impls;

#[cfg(test)]
mod tests;
